### ISSUE TITLE
Add support for ActiveSupport 5

### ISSUE THREAD

**Issue by adomokos** [adomokos/light-service#86]
Right now, LS will break with AS5. I specified `"< 5.0"` for now, but we should make it work with and without 5.0.

**Comment by jeroenvisser101** [comment]
Hey @adomokos, what's the exact issue? Is it related with the changes in StrongParameters?

**Comment by adomokos** [comment]
Deleted all the gems for this project, `bundle install`-ed, ran the specs and this is what I got:

```shell
Failures:

  1) Including is discouraged when including LightService::Action gives warning
     Failure/Error:
       expect(ActiveSupport::Deprecation).to receive(:warn)
         .with(expected_msg)

     NameError:
       uninitialized constant ActiveSupport::Deprecation
       Did you mean?  ActiveSupport::Duration
     # ./spec/acceptance/include_warning_spec.rb:22:in `block (3 levels) in <top (required)>'

  2) Including is discouraged when including LightService::Organizer gives warning
     Failure/Error:
       expect(ActiveSupport::Deprecation).to receive(:warn)
         .with(expected_msg)

     NameError:
       uninitialized constant ActiveSupport::Deprecation
       Did you mean?  ActiveSupport::Duration
     # ./spec/acceptance/include_warning_spec.rb:9:in `block (3 levels) in <top (required)>'

  3) LightService::Context warns about the outcome attribute reader being deprecated
     Failure/Error: expect(ActiveSupport::Deprecation).to receive(:warn)

     NameError:
       uninitialized constant ActiveSupport::Deprecation
       Did you mean?  ActiveSupport::Duration
     # ./spec/context_spec.rb:155:in `block (2 levels) in <top (required)>'

Finished in 0.09118 seconds (files took 0.26582 seconds to load)
97 examples, 3 failures

Failed examples:

rspec ./spec/acceptance/include_warning_spec.rb:19 # Including is discouraged when including LightService::Action gives warning
rspec ./spec/acceptance/include_warning_spec.rb:6 # Including is discouraged when including LightService::Organizer gives warning
rspec ./spec/context_spec.rb:154 # LightService::Context warns about the outcome attribute reader being deprecated
```

And this is what I have for ActiveSupport:

```
bundle show activesupport
/Users/machine/light-service/code/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1
```

I think we should remove the dependency on ActiveSupport honestly. No external gem dependency is a huge win for the project.

**Comment by padi** [comment]
I spent maybe some 30 minutes checking if this is easily doable. Some were easily replaceable, but the one's that will probably take sometime. AS extensions of String methods will need to be replaced, namely `pluralize` and `underscore`. Will submit a PR sometime this weekend.

**Comment by adomokos** [comment]
Thanks @padi!
